#!/usr/bin/env python3

"""
Removes duplicate entries from final annotation summary files.

This script reads the final summary files generated by the annotation pipeline
and removes duplicate rows based on a composite key of the peak coordinate and
the associated gene name, ensuring each peak-gene association is unique.
"""

import argparse
import pandas as pd
import os

def remove_duplicates(input_file, output_file):
    """
    Reads a CSV, removes duplicates based on Coordination and Genename, and saves it.

    Args:
        input_file (str): Path to the input CSV file.
        output_file (str): Path to the de-duplicated output CSV file.
    """
    try:
        df = pd.read_csv(input_file)
    except FileNotFoundError:
        print(f"  Warning: Input file not found: {input_file}. Skipping.")
        return

    # Define the columns that make a row unique
    # The original script used a combination of Coordination, RefSeq, and Genename
    unique_cols = ['Coordination', 'RefSeq', 'Genename']
    
    # Check if required columns exist
    if not all(col in df.columns for col in unique_cols):
        print(f"  Warning: Missing required columns in {input_file}. Required: {unique_cols}. Skipping.")
        return

    num_before = len(df)
    df.drop_duplicates(subset=unique_cols, keep='first', inplace=True)
    num_after = len(df)

    df.to_csv(output_file, index=False)
    print(f"Processed {os.path.basename(input_file)}: Removed {num_before - num_after} duplicates. Saved to {os.path.basename(output_file)}.")

def main():
    """Main function to run the de-duplication script."""
    parser = argparse.ArgumentParser(description="Remove duplicate entries from summary files.")
    parser.add_argument("--input_dir", default="./summary_reports", help="Directory containing the summary files to clean.")
    parser.add_argument("--output_dir", default="./final_reports", help="Directory to save the de-duplicated final reports.")
    args = parser.parse_args()

    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    marks = ["h3k4me3", "h3k27ac", "h3k27me3"]
    file_types = ["All", "TSS", "FC1.5All"]

    for mark in marks:
        for ftype in file_types:
            input_filename = f"summary_{mark}_annotation.{ftype}.final.csv"
            output_filename = f"summary_{mark}_annotation.{ftype}.final.dedup.csv"
            input_path = os.path.join(args.input_dir, input_filename)
            output_path = os.path.join(args.output_dir, output_filename)
            
            remove_duplicates(input_path, output_path)

if __name__ == "__main__":
    main()
